// Mock data for ReelShort clone

export const categories = [
  { id: 1, name: 'Romance', slug: 'romance' },
  { id: 2, name: 'Thriller', slug: 'thriller' },
  { id: 3, name: 'Fantasy', slug: 'fantasy' },
  { id: 4, name: 'Drama', slug: 'drama' },
  { id: 5, name: 'Comedy', slug: 'comedy' },
  { id: 6, name: 'Action', slug: 'action' },
  { id: 7, name: 'Mystery', slug: 'mystery' },
  { id: 8, name: 'Horror', slug: 'horror' },
];

export const shows = [
  {
    id: 1,
    title: 'He Said the Baby Was Too Expensive',
    thumbnail: 'https://images.unsplash.com/photo-1516589178581-6cd7833ae3b2?w=300&h=400&fit=crop',
    category: 'romance',
    rating: 4.8,
    views: '2.5M',
    episodes: 45,
    isExclusive: true,
    description: 'A gripping tale of love, betrayal, and unexpected revelations.',
    duration: '1-3 min per episode',
  },
  {
    id: 2,
    title: "Blood & Silver: Rise of the Alpha's Rejected Mate",
    thumbnail: 'https://images.unsplash.com/photo-1534126511673-b6899657816a?w=300&h=400&fit=crop',
    category: 'fantasy',
    rating: 4.9,
    views: '3.2M',
    episodes: 60,
    isExclusive: true,
    description: 'A werewolf romance filled with power, passion, and revenge.',
    duration: '1-3 min per episode',
  },
  {
    id: 3,
    title: 'Fated to Find You',
    thumbnail: 'https://images.unsplash.com/photo-1518568814500-bf0f8d125f46?w=300&h=400&fit=crop',
    category: 'romance',
    rating: 4.7,
    views: '1.8M',
    episodes: 38,
    isExclusive: false,
    description: 'Destiny brings two souls together in the most unexpected way.',
    duration: '1-3 min per episode',
  },
  {
    id: 4,
    title: "Falling For My Ex's General Dad",
    thumbnail: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=300&h=400&fit=crop',
    category: 'romance',
    rating: 4.6,
    views: '2.1M',
    episodes: 42,
    isExclusive: true,
    description: 'A forbidden romance that defies all expectations.',
    duration: '1-3 min per episode',
  },
  {
    id: 5,
    title: 'The Secret Between US',
    thumbnail: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=300&h=400&fit=crop',
    category: 'thriller',
    rating: 4.8,
    views: '2.9M',
    episodes: 50,
    isExclusive: false,
    description: 'Dark secrets threaten to destroy everything they hold dear.',
    duration: '1-3 min per episode',
  },
  {
    id: 6,
    title: 'Betrayed Alpha Queen Rises from the Ashes',
    thumbnail: 'https://images.unsplash.com/photo-1529626455594-4ff0802cfb7e?w=300&h=400&fit=crop',
    category: 'fantasy',
    rating: 4.9,
    views: '3.5M',
    episodes: 55,
    isExclusive: true,
    description: 'A fallen queen rises to reclaim her throne and her destiny.',
    duration: '1-3 min per episode',
  },
  {
    id: 7,
    title: 'The Art of Letting Go',
    thumbnail: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=300&h=400&fit=crop',
    category: 'drama',
    rating: 4.5,
    views: '1.5M',
    episodes: 32,
    isExclusive: false,
    description: 'Learning to let go is the hardest lesson of all.',
    duration: '1-3 min per episode',
  },
  {
    id: 8,
    title: "Country Gal to CEO's Bride",
    thumbnail: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=300&h=400&fit=crop',
    category: 'romance',
    rating: 4.7,
    views: '2.3M',
    episodes: 40,
    isExclusive: true,
    description: 'From small town girl to the bride of a billionaire CEO.',
    duration: '1-3 min per episode',
  },
  {
    id: 9,
    title: 'Mother Warrior Unleashed',
    thumbnail: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=300&h=400&fit=crop',
    category: 'action',
    rating: 4.8,
    views: '2.7M',
    episodes: 48,
    isExclusive: false,
    description: 'A mother will do anything to protect her family.',
    duration: '1-3 min per episode',
  },
  {
    id: 10,
    title: 'Twilight Romance: Flash Marriage to Mature Tycoon',
    thumbnail: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=300&h=400&fit=crop',
    category: 'romance',
    rating: 4.6,
    views: '2.0M',
    episodes: 36,
    isExclusive: true,
    description: 'A whirlwind marriage leads to unexpected love.',
    duration: '1-3 min per episode',
  },
  {
    id: 11,
    title: 'My Billionaire Ever After',
    thumbnail: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=300&h=400&fit=crop',
    category: 'romance',
    rating: 4.9,
    views: '3.1M',
    episodes: 52,
    isExclusive: true,
    description: 'Finding true love with a billionaire changes everything.',
    duration: '1-3 min per episode',
  },
  {
    id: 12,
    title: 'Married In A Heartbeat',
    thumbnail: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?w=300&h=400&fit=crop',
    category: 'romance',
    rating: 4.7,
    views: '2.4M',
    episodes: 44,
    isExclusive: true,
    description: 'Love at first sight leads to a spontaneous marriage.',
    duration: '1-3 min per episode',
  },
  {
    id: 13,
    title: 'Tell Me Not to Love You',
    thumbnail: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=300&h=400&fit=crop',
    category: 'romance',
    rating: 4.8,
    views: '2.8M',
    episodes: 46,
    isExclusive: false,
    description: 'Sometimes love finds you when you least expect it.',
    duration: '1-3 min per episode',
    isFeatured: true,
  },
  {
    id: 14,
    title: 'The Shadow Conspiracy',
    thumbnail: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=300&h=400&fit=crop',
    category: 'thriller',
    rating: 4.9,
    views: '3.0M',
    episodes: 58,
    isExclusive: true,
    description: 'Uncover the truth before it\'s too late.',
    duration: '1-3 min per episode',
  },
  {
    id: 15,
    title: 'Hidden Identity',
    thumbnail: 'https://images.unsplash.com/photo-1464746133101-a2c3f88e0dd9?w=300&h=400&fit=crop',
    category: 'mystery',
    rating: 4.7,
    views: '2.2M',
    episodes: 41,
    isExclusive: false,
    description: 'Who is she really? The truth will shock you.',
    duration: '1-3 min per episode',
  },
];

// Generate episodes for each show
export const generateEpisodes = (showId, totalEpisodes) => {
  const episodes = [];
  for (let i = 1; i <= totalEpisodes; i++) {
    episodes.push({
      id: `${showId}-${i}`,
      episodeNumber: i,
      title: `Episode ${i}`,
      duration: Math.floor(Math.random() * 120) + 60, // 60-180 seconds
      isLocked: i > 5, // First 5 episodes are free
      thumbnail: `https://images.unsplash.com/photo-${1500000000000 + showId * 1000 + i}?w=200&h=120&fit=crop`,
      coinsRequired: i > 5 ? Math.floor(Math.random() * 50) + 10 : 0,
    });
  }
  return episodes;
};

export const user = {
  id: 1,
  name: 'Guest User',
  email: 'guest@reelshort.com',
  avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&h=150&fit=crop',
  coins: 150,
  watchlist: [1, 3, 6, 13],
  watchHistory: [
    { showId: 13, episodeNumber: 3, timestamp: new Date('2025-07-10') },
    { showId: 1, episodeNumber: 5, timestamp: new Date('2025-07-09') },
    { showId: 6, episodeNumber: 8, timestamp: new Date('2025-07-08') },
  ],
};
